### ISSUE TITLE
Module not working in survey mode ?

### ISSUE THREAD

**Issue by MathiasAntunes** [criwebtools/Second-Language#1]
Hi, thank you for the module. I've been testing it, but it does not seem to work in survey mode, is this intended behaviour ?
Thx

**Comment by criwebtools** [comment]
Hi Mathias,

Thanks for the information. We designed second language as a simplified
alternative to the "Multilanguage" module, and it really only supports
traditional, interviewer-managed questionnaires. Our main goal was to
improve the designer UI so that we could bang out very large questionnaires
as quickly as possible.The Multilanguage module has very extensive support
for surveys.

I will more clearly state the limitations of Second Language, and take a
look at the possibility of basic survey support. Very sorry if you've lost
time on this issue-

Pete

**Comment by MathiasAntunes** [comment]
Hi Pete,

Thanks for the answer.
